fixes:
  - "/home/runner/work/felipegutierrez/explore-spring/::" # Correct paths
coverage:
  precision: 2
  round: nearest
  range: "40...70"
#  ignore:
#     - "Employee/src/main/java/EmployeeCommon/EmployeeScreensParameterService.java"

