spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      client-id: json-pos-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  cloud:
    stream:
      bindings:
        notification-input-channel:
          destination: pos-topic
        notification-output-avro-channel:
          destination: loyalty-avro-topic
        hadoop-input-channel:
          destination: pos-topic
        hadoop-output-avro-channel:
          destination: hadoop-sink-avro-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
          bindings:
            notification-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
application:
  configs:
    users.topic.name: users
    invoice.count: 60
    invoice.topic.json.name: pos-topic
    invoice.topic.avro.name: pos-avro-topic
    loyalty.topic.avro.name: loyalty-avro-topic
    hadoop.topic.avro.name: hadoop-sink-avro-topic
---
