spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      client-id: json-pos-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group-01
  cloud:
    stream:
      bindings:
        notification-input-channel:
          destination: pos-topic
        notification-output-avro-channel:
          destination: loyalty-avro-topic
        hadoop-input-channel:
          destination: pos-topic
        hadoop-output-avro-channel:
          destination: hadoop-sink-avro-topic
        notification-input-avro-channel:
          destination: pos-avro-topic
        notification-output-json-channel:
          destination: loyalty-topic
        hadoop-input-avro-channel:
          destination: pos-avro-topic
        hadoop-output-json-channel:
          destination: hadoop-sink-topic
        pos-input-avro-exactly-once-channel:
          destination: pos-avro-topic
        xml-input-channel:
          destination: xml-order-topic
        india-orders-channel:
          destination: india-orders-topic
        abroad-orders-channel:
          destination: abroad-orders-topic
        stock-input-channel:
          destination: stock-tick-topic
        words-input-channel:
          destination: streaming-words-topic
          consumer:
            useNativeDecoding: false
            contentType: text/plain
        employee-input-channel:
          destination: employees-topic
        invoice-input-channel:
          destination: simple-invoice-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              processing.guarantee: exactly_once
              commit.interval.ms: 10000
              state.dir: state-store
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            notification-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            notification-input-avro-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            notification-output-json-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            hadoop-input-avro-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-output-json-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            pos-input-avro-exactly-once-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            india-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            abroad-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            stock-input-channel:
              consumer:
                materializedAs: stock-input-store
            words-input-channel:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            employee-input-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            invoice-input-channel:
              consumer:
                timestampExtractorBeanName: invoiceTimesExtractor
application:
  configs:
    users.topic.name: users
    invoice.count: 60
    invoice.topic.json.name: pos-topic
    invoice.topic.avro.name: pos-avro-topic
    loyalty.topic.avro.name: loyalty-avro-topic
    loyalty.topic.json.name: loyalty-topic
    hadoop.topic.avro.name: hadoop-sink-avro-topic
    hadoop.topic.json.name: hadoop-sink-topic
    hadoop.topic.avro.ex.name: hadoop-sink-avro-ex-topic
    loyalty.topic.avro.ex.name: loyalty-avro-ex-topic
    order.xml.input.topic.name: xml-order-topic
    order.india.output.topic.name: india-orders-topic
    order.abroad.output.topic.name: abroad-orders-topic
    order.error.topic.name: order-error-topic
    stock.tick.topic.name: stock-tick-topic
    words.streaming.topic.name: streaming-words-topic
    words.streaming.output.topic.name: streaming-words-output-topic
    employees.input.topic.name: employees-topic
    simple.invoice.input.topic: simple-invoice-topic
---
