spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      client-id: json-pos-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  cloud:
    stream:
      bindings:
        notification-input-channel:
          destination: pos-topic
        notification-output-avro-channel:
          destination: loyalty-avro-topic
        hadoop-input-channel:
          destination: pos-topic
        hadoop-output-avro-channel:
          destination: hadoop-sink-avro-topic
        notification-input-avro-channel:
          destination: pos-avro-topic
        notification-output-json-channel:
          destination: loyalty-topic
        hadoop-input-avro-channel:
          destination: pos-avro-topic
        hadoop-output-json-channel:
          destination: hadoop-sink-topic
        pos-input-avro-exactly-once-channel:
          destination: pos-avro-topic
        xml-input-channel:
          destination: xml-order-topic
        india-orders-channel:
          destination: india-orders-topic
        abroad-orders-channel:
          destination: abroad-orders-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              processing.guarantee: exactly_once
          bindings:
            notification-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-output-avro-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            notification-input-avro-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            notification-output-json-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            hadoop-input-avro-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            hadoop-output-json-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            pos-input-avro-exactly-once-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            india-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
            abroad-orders-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
application:
  configs:
    users.topic.name: users
    invoice.count: 60
    invoice.topic.json.name: pos-topic
    invoice.topic.avro.name: pos-avro-topic
    loyalty.topic.avro.name: loyalty-avro-topic
    loyalty.topic.json.name: loyalty-topic
    hadoop.topic.avro.name: hadoop-sink-avro-topic
    hadoop.topic.json.name: hadoop-sink-topic
    hadoop.topic.avro.ex.name: hadoop-sink-avro-ex-topic
    loyalty.topic.avro.ex.name: loyalty-avro-ex-topic
    order.xml.input.topic.name: xml-order-topic
    order.india.output.topic.name: india-orders-topic
    order.abroad.output.topic.name: abroad-orders-topic
    order.error.topic.name: order-error-topic
---
