spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  data.mongodb:
    uri: ${MONGODB_URI:mongodb://root:rootpassword@localhost:27017/local?authSource=admin}
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  config:
    activate:
      on-profile: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
