spring:
  profiles:
    active: dev
---
topic:
  name: library-events
  partitions-num: 1
  replication-factor: 1
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    template:
      default-topic: library-events
    producer:
      # bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    properties:
      schema.registry.url: http://127.0.0.1:8081
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        # bootstrap.servers: localhost:9092
---
topic:
  name: library-events
  partitions-num: 1
  replication-factor: 1
spring:
  config:
    activate:
      on-profile: test # test profile does not use KafkaJsonSchemaSerializer and schema.registry
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        # bootstrap.servers: localhost:9092

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
