/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.felipegutierrez.explore.spring.java-conventions")
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.3")
    implementation("org.springframework.boot:spring-boot-devtools:2.4.3")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.4.3")
    implementation("org.springframework.data:spring-data-rest-hal-browser:3.3.7.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.3")
    testImplementation("org.springframework:spring-test:5.3.4")
    testImplementation("org.mockito:mockito-core:3.6.28")
    testImplementation("org.mockito:mockito-junit-jupiter:2.23.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.1")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.2.0")
    testImplementation("org.codehaus.mojo:cobertura-maven-plugin:2.7")
}

description = "spring-web"
