# bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml
# - run: mvn cobertura:cobertura # Run test
# - run: bash <(curl -s https://codecov.io/bash)
name: Run Test Suites

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out your repository
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn verify -P coverage # Run test
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov # Upload to Codecov
